### PR TITLE
End of Sprint2 sync to master

### PR DESCRIPTION
**Pull request by doyougnu**
# What this PR adds
This PR adds a front end view for manipulating summaries, reading introductions to files, and downloading files

# How to test this
Run the tests in the backend, run the tests in the front end. Still not satisified? Then start click testing!

### CODE REVIEW

**Comment by mihaidan** [comment]
build failed with the error message `no module named 'bs4'`

**Comment by mihaidan** [comment]
build failed with the error message `TypeError: expected str, bytes or os.PathLike object, not list`

**Comment by doyougnu** [comment]
Added beautiful soup 4 to dependencies, fixed default argument type error in e61f63041a3b98fea62699b369068fc83ffaa090

**Review by mihaidan — APPROVED** [review]
I'm Mihai and this PR updates our master branch to the progress made up until the end of Sprint 2. Looks good

**Pull request merged**
